---
jobs:
- name: build-docker-image
  public: true
  serial: true
  plan:
    - get: hello_hapi
      trigger: true
    - put: docker-image
      params:
        build: hello_hapi/ci
    - task: run the test suite
      file: hello_hapi/ci/tasks/run_tests.yml
resources:
  - name: hello_hapi
    type: git
    check_every: 5m
    source:
      uri: https://github.com/teamsampleproject/nodeJSPOC
      branch: master
      private_key:

  - name: docker-image
    type: docker-image
    source:
      email: ggopikrishna2012@gmail.com
      username: 308017
      password: gopi1985!@#
      repository: sampleuiproject1